name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Lint code
        working-directory: backend
        run: npm run lint

      - name: Run tests
        working-directory: backend
        run: npm test
