name: Deploy to Fly.io

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to fly
        working-directory: ./backend
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
