name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Lint
        run: cd frontend && npm run lint

      - name: Unit Tests
        run: cd frontend && npm run test

      - name: Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          build: cd frontend && npm run build
          start: cd frontend && npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
