name: Smart contract CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SEPOLIA_RPC_URL: ${{secrets.SEPOLIA_RPC_URL}}
      SEPOLIA_PRIVATE_KEY: ${{secrets.SEPOLIA_PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
      UPDATE_FRONT_END: ${{secrets.UPDATE_FRONT_END}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2

      - name: Install dependencies
        working-directory: DAppProperty
        run: yarn install --frozen-lockfile

      - name: Lint code
        working-directory: DAppProperty
        run: yarn run lint

      - name: Run tests
        working-directory: DAppProperty
        run: yarn run test
